import { useState, useRef } from 'react'
import { useNavigate } from 'react-router-dom'
import { supabase } from '../lib/supabase'

export default function ImportPage() {
  const navigate = useNavigate()
  const fileInputRef = useRef()
  const audioInputRef = useRef()

  const [manifest, setManifest] = useState(null)
  const [audioFile, setAudioFile] = useState(null)
  const [phase, setPhase] = useState('idle') // idle | loading | importing | done | error
  const [progress, setProgress] = useState('')
  const [error, setError] = useState('')

  const handleManifestDrop = (e) => {
    e.preventDefault()
    const file = e.dataTransfer?.files?.[0] || e.target.files?.[0]
    if (!file) return
    const reader = new FileReader()
    reader.onload = (ev) => {
      try {
        const data = JSON.parse(ev.target.result)
        setManifest(data)
        setError('')
      } catch {
        setError('Invalid JSON file.')
      }
    }
    reader.readAsText(file)
  }

  const handleAudioChange = (e) => {
    setAudioFile(e.target.files?.[0] || null)
  }

  const handleImport = async () => {
    if (!manifest) return
    setPhase('importing')
    setError('')

    try {
      const { data: { user } } = await supabase.auth.getUser()
      if (!user) throw new Error('Not logged in.')

      setProgress('Creating project record…')
      const { data: proj, error: projErr } = await supabase.from('projects').insert({
        user_id: user.id,
        title: manifest.title || 'Kawanakajima',
        status: 'videos_ready',
        script: manifest.script || '',
        brief: manifest.brief || null,
        cost_cents: manifest.brief?.cost_estimate?.total_usd
          ? Math.round(manifest.brief.cost_estimate.total_usd * 100)
          : 0,
        thumbnail_url: manifest.scenes?.[0]?.image_url || null,
      }).select().single()
      if (projErr) throw projErr

      setProgress('Inserting scene records…')
      const sceneRows = manifest.scenes.map((s) => ({
        project_id: proj.id,
        scene_index: s.scene_index,
        description: s.description || '',
        image_prompt: s.image_prompt || '',
        motion_prompt: s.motion_prompt || '',
        image_url: s.image_url || null,
        video_url: s.video_url || null,
        status: 'complete',
      }))
      const { error: scenesErr } = await supabase.from('scenes').insert(sceneRows)
      if (scenesErr) throw scenesErr

      if (audioFile) {
        setProgress('Uploading audio…')
        const ext = audioFile.name.split('.').pop()
        const storagePath = `${user.id}/${proj.id}/audio.${ext}`
        const { error: uploadErr } = await supabase.storage
          .from('project-assets')
          .upload(storagePath, audioFile, { contentType: audioFile.type, upsert: true })
        if (uploadErr) throw uploadErr

        const { data: { publicUrl } } = supabase.storage
          .from('project-assets')
          .getPublicUrl(storagePath)

        await supabase.from('projects').update({ audio_url: publicUrl }).eq('id', proj.id)
      }

      setProgress('Done.')
      setPhase('done')
      setTimeout(() => navigate(`/project/${proj.id}`), 1200)
    } catch (err) {
      setError(err.message || 'Import failed.')
      setPhase('error')
    }
  }

  return (
    <div className="app-layout">
      <header className="app-header">
        <div className="header-left">
          <button className="btn-ghost" onClick={() => navigate('/dashboard')}>← Dashboard</button>
          <span className="header-brand-mark">⛩</span>
          <span className="header-brand">Import Pipeline Result</span>
        </div>
      </header>

      <main className="project-main" style={{ maxWidth: 640, margin: '48px auto' }}>
        <h2 style={{ marginBottom: 8 }}>Import from JSON Manifest</h2>
        <p style={{ color: 'var(--text-dim)', marginBottom: 32 }}>
          Load a <code>kawanakajima-manifest.json</code> file generated by the pipeline script,
          optionally attach an audio file, then import into Supabase.
        </p>

        {/* Manifest drop zone */}
        <div
          className="audio-drop-zone"
          style={{ marginBottom: 24, cursor: 'pointer' }}
          onClick={() => fileInputRef.current?.click()}
          onDrop={handleManifestDrop}
          onDragOver={(e) => e.preventDefault()}
        >
          <input
            ref={fileInputRef}
            type="file"
            accept=".json,application/json"
            style={{ display: 'none' }}
            onChange={handleManifestDrop}
          />
          {manifest ? (
            <div>
              <p style={{ color: 'var(--gold)', fontWeight: 600, marginBottom: 4 }}>
                ✓ {manifest.title || 'Manifest loaded'}
              </p>
              <p style={{ color: 'var(--text-dim)', fontSize: 14 }}>
                {manifest.scenes?.length} scenes · Click to replace
              </p>
            </div>
          ) : (
            <p>Drop <strong>kawanakajima-manifest.json</strong> here or click to browse</p>
          )}
        </div>

        {/* Audio picker */}
        <div style={{ marginBottom: 32 }}>
          <label style={{ display: 'block', marginBottom: 8, fontWeight: 600 }}>
            Audio file (optional — m4a, mp3, wav)
          </label>
          <input
            ref={audioInputRef}
            type="file"
            accept="audio/*,.m4a,.mp3,.wav,.aac"
            onChange={handleAudioChange}
            style={{ color: 'var(--text)' }}
          />
          {audioFile && (
            <p style={{ color: 'var(--gold)', fontSize: 13, marginTop: 6 }}>
              ✓ {audioFile.name} ({(audioFile.size / 1024).toFixed(0)} KB)
            </p>
          )}
        </div>

        {/* Error */}
        {error && <p className="error-message" style={{ marginBottom: 16 }}>{error}</p>}

        {/* Progress */}
        {phase === 'importing' && (
          <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 24 }}>
            <div className="spinner" />
            <p>{progress}</p>
          </div>
        )}
        {phase === 'done' && (
          <p style={{ color: '#4caf50', marginBottom: 24 }}>✓ Imported! Redirecting to project…</p>
        )}

        <button
          className="btn-primary"
          onClick={handleImport}
          disabled={!manifest || phase === 'importing' || phase === 'done'}
          style={{ minWidth: 180 }}
        >
          {phase === 'importing' ? 'Importing…' : 'Import Project →'}
        </button>

        {manifest && (
          <details style={{ marginTop: 40 }}>
            <summary style={{ cursor: 'pointer', color: 'var(--text-dim)' }}>
              Preview manifest ({manifest.scenes?.length} scenes)
            </summary>
            <div style={{ marginTop: 16, display: 'flex', flexDirection: 'column', gap: 16 }}>
              {manifest.scenes?.map((s, i) => (
                <div key={i} style={{ display: 'flex', gap: 12, alignItems: 'flex-start' }}>
                  {s.image_url && (
                    <img
                      src={s.image_url}
                      alt={`Scene ${i + 1}`}
                      style={{ width: 80, height: 142, objectFit: 'cover', borderRadius: 4, flexShrink: 0 }}
                    />
                  )}
                  <div>
                    <p style={{ fontWeight: 600, marginBottom: 4 }}>Scene {i + 1}</p>
                    <p style={{ fontSize: 13, color: 'var(--text-dim)' }}>{s.description}</p>
                  </div>
                </div>
              ))}
            </div>
          </details>
        )}
      </main>
    </div>
  )
}
